#!/bin/csh -fx

#set top = `(chdir .. ; pwd)`
set top = `pwd`

setenv CC 	"gcc -m32"
setenv CXX 	"g++ -m32"

set	build_curl	= 1
set	build_xmlrpc	= 1


echo "Building support libraries ...."
echo "  (Using toplevel directory '"$top"' ....)"

# Global options.
set	gopts = "--prefix=$top --exec-prefix=$top --disable-shared"

#echo "    Cleaning files ...."
#./mkclean

if ($build_curl == 1) then

  echo -n  "    Building CURL libs ...."
  set	opts = "$gopts \
		--disable-ftp \
		--disable-file \
		--disable-ldap \
		--disable-ldaps \
		--disable-proxy \
		--disable-dict \
		--disable-telnet \
		--disable-tftp \
		--disable-manual \
		--disable-ipv6 \
		--disable-ares \
		--disable-sspi \
		--disable-crypto-auth \
		--without-krb4 \
		--without-ssl \
		--without-zlib \
		--without-libssh2 \
		--without-gnutls \
		--without-nss \
		--without-ca-path \
		--without-libidn"
  
 (chdir curl-7.30.0 ;  \
   ./configure $opts  				 >& _spool ; \
   make clean 					>>& _spool ; \
   make 					>>& _spool ; \
   make install 				>>& _spool ; \
   make clean 					>>& _spool  )

  	echo "done"
	pwd
	cp ./curl-7.30.0/lib/.libs/libcurl.a ../lib/

endif


#chdir lib/build
#ar x ../libcurl.a
#/bin/rm -f ../libcurl.a
#foreach i (*)
#     mv $i curl_$i
#end
#ar r ../libcurl.a *.o
#ranlib ../libcurl.a
#chdir ../../



setenv CC 	"gcc -m32 -g -ggdb -O0"
setenv CXX 	"g++ -m32 -g -ggdb -O0"

if ($build_xmlrpc == 1) then

echo -n "    Building XMLRPC-C libs ...."
  set	opts = "$gopts \
		--enable-curl-client \
		--disable-wininet-client \
		--disable-libwww-client \
		--disable-cplusplus \
		--disable-cgi-server"
		#--disable-abyss-threads \
# was 32
# was 38
  (chdir xmlrpc-c-1.25.23 ;  \
    echo $opts 					 >& _opts  ; \
    ./travisconfigure $opts  				 >& _spool ; \
    make clean 					>>& _spool ; \
    make 					>>& _spool ; \
    make install 				>>& _spool ; \
    ./traviscopylibs   				>>& _spool)
echo "done"

endif

# Clean up.
/bin/rm -rf lib/*.la lib/*.so.* lib/*.so lib/pkgconfig
find . -name blddir -print -exec rm -f {} \;
find . -name srcdir -print -exec rm -f {} \;


# Now build the combined library.
chdir lib/build
ls ../lib*.a
    foreach i (../lib*.a)
	set lname = `echo $i | sed -e 's/lib//g' -e 's/\.a//' -e 's/xmlrpc_//g' -e 's/server_//g' | cut -c4-`

        ar x $i
	foreach j (*.o)
	    mv $j ${lname}_$j
	    chmod 444 ${lname}_$j
	end
        ar r ../../libxrpc.a *.o *.a
        ranlib ../../libxrpc.a
	/bin/rm -f *.o
    end

		# build_xmlrpc

chdir ../..
