DAL Client Library: dalQuery.c File Reference
dalQuery.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
#include <ctype.h>
#include <float.h>
#include "dalclient.h"
Functions
DAL dal_openConnection (char *baseurl, char *protocol, char *version)
DAL dal_openConeConnection (char *baseurl, char *version)
DAL dal_openSiapConnection (char *baseurl, char *version)
DAL dal_openSsapConnection (char *baseurl, char *version)
void dal_closeConnection (DAL dal_h)
void dal_setBaseUrl (DAL dal_h, char *base_url)
char * dal_getBaseUrl (DAL dal_h)
Query dal_getQuery (DAL dal_h)
void dal_closeQuery (Query query_h)
Query dal_getConeQuery (DAL dal_h, double ra, double dec, double sr)
Query dal_getSiapQuery (DAL dal_h, double ra, double dec, double ra_size, double dec_size, char *format)
Query dal_getSsapQuery (DAL dal_h, double ra, double dec, double size, char *band, char *time, char *format)
Query dal_getAccessDataQuery (DAL dal_h)
int dal_getParamCount (Query query_h)
char * dal_getParamName (Query query_h, int index)
int dal_addIntParam (Query query_h, char *pname, long value)
int dal_addFloatParam (Query query_h, char *pname, double value)
int dal_addStringParam (Query query_h, char *pname, char *value)
int dal_setParam (Query query_h, char *pname, char *value)
char * dal_getParam (Query query_h, char *pname, int index)
int dal_delParam (Query query_h, char *pname)
char * dal_getQueryURL (Query query_h)
int dal_getError (DAL dal_h)
char * dal_getErrorMsg (DAL dal_h)
void dal_clearError (DAL dal_h)
int dal_error (dalConn_t *dal, int errcode)
void dal_setErrorMsg (dalConn_t *dal, char *errmsg)
void * dal_nError (dalConn_t *dal, int errcode)
int dal_qError (dalQuery_t *query, int errcode)
int dal_qrError (dalQR_t *qr, int errcode)
Detailed Description
DALQUERY -- Compose a query to a VO Data Access Layer (DAL) Service.
These routines are used to create a DALClient context to be used to query a DAL service, and then compose the query.
---- Service Connection ---------
dal = dal_openConnection (baseurl, protocol, version) dal = dal_openConeConnection (baseurl, version) dal = dal_openSiapConnection (baseurl, version) dal = dal_openSsapConnection (baseurl, version) dal_closeConnection (dal)
dal_setBaseUrl (dal, url) # setters/getters url = dal_getBaseUrl (dal)
errcode = dal_getError (dal) dal_clearError (dal)
---- Query Parameters ---------
query = dal_getQuery (dal) dal_closeQuery (query) # free resources
query = dal_getConeQuery (dal, ra, dec, sr) query = dal_getSiapQuery (dal, ra, dec, ra_size, dec_size, format) query = dal_getSsapQuery (dal, ra, dec, size, band, time, format)
query = dal_genConeQuery (dal, pos) query = dal_genSiapQuery (dal, pos, band, time, pol, format, mode) query = dal_genSsapQuery (dal, pos, band, time, pol, format, mode)
pos = dal_getObjPos (objname|NULL) pos = dal_setPos (c1, c2, size, frame|NULL) pos = dal_setPos2 (c1, c2, size1, size2, frame|NULL) <additional-constructors> <additional-setters> dal_posGetCoords (pos, c1, c2, &frame) dal_closePos (pos)
int = dal_getParamCount (query) str = dal_getParamName (query, index) stat = dal_addIntParam (query, pname, ival) stat = dal_addFloatParam (query, pname, dval) stat = dal_addStringParam (query, pname, str) dal_setParam (query, pname, str) str = dal_getParam (query, pname, index) dal_delParam (query, pname)
str = dal_getQueryURL (query)
A separate connection is required for each service to be queried. Simple queries may be composed directly via a service class-specific constructor, or queries may be built up with parameters, or both.
All public routines in this interface that return an object handle, e.g., for a Dal or Query object, return an opaque object handle (not a normal C object pointer).
Author:
Doug Tody
Version:
January 2014
Function Documentation
int dal_error (dalConn_t * dal, int errcode)
dal_error -- Post an error for the connection.
The given error code is stored in the DAL connection context for later retrieval. The error status is saved until explicitly cleared. DAL_ERROR is returned as the status value, allowing the error status to be posted within a return statement.
Referenced by dal_qError(), and dal_qrError().
void* dal_nError (dalConn_t * dal, int errcode)
dal_nError -- Post an error for the connection, returning NULL. NULL is returned as the status value, allowing the error status to be posted within a return statement.
int dal_qError (dalQuery_t * query, int errcode)
dal_qError -- Convenience routine for posting an error within the query construction code.
References dal_error().
int dal_qrError (dalQR_t * qr, int errcode)
dal_qrError -- Convenience routine for posting an error within the query response code.
References dal_error().
void dal_setErrorMsg (dalConn_t * dal, char * errmsg)
dal_setErrorMsg -- Set the error message string.