DAL Client Library: vocHash.c File Reference
vocHash.c File Reference
#include <stdlib.h>
#include <string.h>
#include <ctype.h>
#include "vocHash.h"
Functions
vocHash_t * vht_init (size_t size, int(*hash_func)(void *, size_t, size_t), char *flag)
void * vht_search (vocHash_t *hashtable, void *key, size_t keylen)
void * vht_findKey (vocHash_t *hashtable, char *key)
void * vht_insert (vocHash_t *hashtable, void *key, size_t keylen, void *value, size_t vallen)
void * vht_insertKey (vocHash_t *hashtable, char *key, void *value)
void vht_remove (vocHash_t *hashtable, void *key, size_t keylen)
void vht_removeKey (vocHash_t *hashtable, char *key)
void * vht_grow (vocHash_t *old_ht, size_t new_size)
void vht_destroy (vocHash_t *hashtable)
void vht_iter_init (vocHash_t *hashtable, vocHash_iter_t *ii)
void vht_iter_inc (vocHash_iter_t *ii)
int vht_hash (void *key, size_t keylen, size_t hashtab_size)
Detailed Description
VOCHASH - Simple C Hashtable Class.
vht = vht_init (size, hash_func, flag) obj = vht_search (vht, key, keylen) obj = vht_findKey (vht, stringKey) obj = vht_insert (vht, key, keylen, value, vallen) obj = vht_insertKey (vht, stringKey, value, vallen) vht_remove (vht, key, keylen) vht_removeKey (vht, stringKey) vht_grow (vht, new_size) vht_destroy (vht)
vht_iter_init (vht, iterator) vht_iter_inc (iterator) vht_hash (key, keylen, hashtab_size
The hash table may be any size, set when initially created, and may be nondestructively grown during usage if desired. Growing does not happen automatically, nor is it strictly required, but the hash table can become inefficient if multiple keys has to the same hash slot.
Both keys and values are opaque objects and may be any size. Convenience routines are provided for string-valued keys. A custom hash function may be supplied at init time to hash whatever type of key is supplied. A default has function that merely hashes a sequence of bytes is provided and is the default if no hash function is supplied.
Original by C.Wellons; adapted for VOClient usage by D.Tody Dec 2013
Author:
Doug Tody
Version:
December 2013
Function Documentation
void vht_destroy (vocHash_t * hashtable)
vht_destroy -- Free all resources used by the hashtable.
hashtable Hashtable to be destroyed.
Referenced by vht_grow().
void* vht_findKey (vocHash_t * hashtable, char * key)
vht_findKey -- Convenience routine to search for a string-valued key.
hashtable Hashtable to be used key Hash key to search for
This routine is limited to string-valued keys. What is returned is a pointer to the external Value object originally input to vht_insertKey.
References vht_search().
void* vht_grow (vocHash_t * old_ht, size_t new_size)
ht_grow -- Grow the hashtable.
old_ht Hash table to be modified. new_size N hash slots in new table.
A pointer to the new hash table is returned upon successful completion, otherwise NULL. If an error occors the old hash table is unmodified.
References vht_destroy(), vht_init(), vht_insert(), vht_iter_inc(), and vht_iter_init().
int vht_hash (void * key, size_t keylen, size_t hashtab_size)
vht_hash -- Default, generic hash function.
key Key to be hashed keylen Size in bytes of the key hashtab_size Number of slots in hash table
Referenced by vht_init(), vht_insert(), vht_remove(), and vht_search().
vocHash_t* vht_init (size_t size, int(*)(void *, size_t, size_t) hash_func, char * flag)
vht_init -- Create a new, empty hash table.
size N slots in initial hash table hash_func Hash function (optional, may be NULL) flag Set to "case" (default) or "nocase"
A unique key is determined by the hash value of the key data and the keylen in bytes. In this implementation, only a single instance of a key is permitted; inserts for the same key overwrite the old instance. A possible future enhancement would be to permit multiple instances with the same key.
References vht_hash().
Referenced by vht_grow().
void* vht_insert (vocHash_t * hashtable, void * key, size_t keylen, void * value, size_t vallen)
vht_insert -- Insert a key, value pair in the hash table.
hashtable Hashtable to be used key Ptr to the key keylen Size in bytes of the key value Ptr to the value vallen Size in bytes of value data
If a matching key,keylen entry already exists (key and keylen identical) it is updated. If the insertion is successful a pointer to the value element is returned, otherwise NULL is returned.
References vht_hash().
Referenced by vht_grow(), and vht_insertKey().
void* vht_insertKey (vocHash_t * hashtable, char * key, void * value)
vht_insertKey -- Convenience routine to insert a string-valued key.
hashtable Hash table to be used key Key to be hashed value Pointer to external data object
This routine is limited to string-valued keys. Value is a pointer to some external object. Unlike vht_insert, the content of the Value object is not copied into internal storage, rather only the value of the Value object pointer is stored.
References vht_insert().
void vht_iter_inc (vocHash_iter_t * ii)
vht_iter_inc -- Incrememt the iterator.
ii Active iterator
Referenced by vht_grow(), and vht_iter_init().
void vht_iter_init (vocHash_t * hashtable, vocHash_iter_t * ii)
vht_iter_init -- Initialize a new hash table iterator.
hashtable Hashtable to be iterated ii Iterator
References vht_iter_inc().
Referenced by vht_grow().
void vht_remove (vocHash_t * hashtable, void * key, size_t keylen)
vht_remove - Delete the given key from the hashtable.
hashtable Hash table to be used key Key to be removed keylen Key length (must match)
It is not an error if the key is not found.
References vht_hash().
Referenced by vht_removeKey().
void vht_removeKey (vocHash_t * hashtable, char * key)
vht_removeKey -- Convenience routine to remove a string-valued key.
References vht_remove().
void* vht_search (vocHash_t * hashtable, void * key, size_t keylen)
vht_search -- Look up the given key in the hash table, returning a pointer to the found entry, or NULL.
hashtable Hashtable to be searched key Hash key keylen Hash key length
The hash key datatype and size is arbitrary but must agree with what the hash function expects.
References vht_hash().
Referenced by vht_findKey().