DAL Client Library: vocList.c File Reference
vocList.c File Reference
#include <stdlib.h>
#include <string.h>
#include <stdio.h>
#include "vocList.h"
Functions
vocList_t * vll_init (long req_size)
Create a new linked ist.
long vll_count (vocList_t *list)
Get the current size of the list.
void * vll_seek (vocList_t *list, long offset, int whence)
Seek to the indicated position in the list.
void * vll_find (vocList_t *list, void *obj, long *index)
void * vll_prev (vocList_t *list)
Get the previous element in the list.
void * vll_next (vocList_t *list)
Get the next element in the list.
void * vll_insert (vocList_t *list, void *obj, long *index)
void * vll_append (vocList_t *list, void *obj, long *index)
void * vll_remove (vocList_t *list, long req_pos)
Remove a node from the list.
void vll_destroy (vocList_t *list, void(*func)(void *ptr))
Destroy the List object and free resources.
int vll_rebuild_index (vocList_t *list, int req_size)
Rebuild the array index.
Detailed Description
VOCLIST.C - Simple C Array-List Class.
Lists are doubly-linked, with the value being a pointer to an arbitrary external object. The life cycle of the external object is not managed by the list. An unusual feature is that an array index is supported to permit randomly accessing the list as an array.
list = vll_init (size) # create with initial size len = vll_count (list) # get current list length obj = vll_seek (list, offset, whence) # seek to offset from whence obj = vll_find (list, obj, index) # find next node with object obj = vll_prev (list) # back up one node obj = vll_next (list) # advance to next node obj = vll_insert (list, obj, index) # insert at current pos obj = vll_append (list, obj, index) # append to the list obj = vll_remove (list, pos) # remove node from list vll_destroy (list, func) # free all list resources
The list may be traversed in either direction or may be randomly accessed like an array. The access methods (e.g., seek, prev, next) return a pointer to the object associated with the current list node.
Note: This code is optimized for fairly static lists to which items are mainly appended. The need to maintain an index into the list requires that the index be rebuilt if elements are inserted or removed anywhere other than at the end of the list. Note that rebuilding the index can cause index values for nodes to change. Appending to the list has no performance penalty. These considerations affect only efficiency; inserting and removing elements at random is otherwise not affected.
Author:
Doug Tody
Version:
January 2014
Function Documentation
long vll_count (vocList_t * list)
Get the current size of the list.
vll_count -- Return a count of the current number of list elements.
Parameters:
list Linked list to be accessed
Returns:
Number of items currently in the List
vll_destroy (vocList_t * list, void(*)(void *ptr) func)
Destroy the List object and free resources.
vll_destroy -- Destroy a List object and free all resources.
Parameters:
list Linked List object to be destroyed.
func Optional object delete function
Returns:
No return value
A pointer to a function to delete the "value" elements of nodes may optionally be specified, otherwise this operation only affects the list itself, and the external objects referenced in list elements are not affected. The signature for FUNC is the same as free().
list vll_init (long size)
Create a new linked ist.
vll_init -- Create a new, empty linked list.
Parameters:
size Initial max size of list, or 0 for default
Returns:
Reference to List object
A new, empty list is created. Initial storage for the index array used to randomly access the list may optionally be specified as SIZE. If SIZE=0, a default maximum size will be used. The maximum size of the list is a soft maximum, i.e., the list will be grown automatically as needed.
obj vll_next (vocList_t * list)
Get the next element in the list.
vll_next -- Seek to the next position in the list.
Parameters:
list Linked list to be accessed
Returns:
Pointer to the object stored at that node
If the seek position is valid a pointer to the object at that location is returned, otherwise NULL. Attempting to seek beyond the end of the list results in NULL being returned.
References vll_seek().
obj vll_prev (vocList_t * list)
Get the previous element in the list.
vll_prev -- Seek to the previous position in the list.
Parameters:
list Linked list to be accessed
Returns:
Pointer to the object stored at that node
If the seek position is valid a pointer to the object at that location is returned, otherwise NULL. Attempting to seek beyond the beginning of the list results in NULL being returned.
References vll_seek().
vll_rebuild_index (vocList_t * list, int req_size)
Rebuild the array index.
vll_rebuild_index -- Internal routine to reallocate and rebuild the array index for the list if it overflows, or if elements are deleted other than at the end.
Parameters:
list Linked List object to be destroyed.
size Size for the new list, or zero if no change.
Returns:
Execution status code
EXIT_SUCCESS is returned if the new index is created successfully, otherwise EXIT_FAILURE. If an error occurs the old index is not replaced, but may no longer be valid (depending upon the calling routine).
Referenced by vll_remove().
vll_remove (vocList_t * list, long req_pos)
Remove a node from the list.
vll_remove -- Remove the node at the given position from the list.
Parameters:
list Linked list to be accessed.
pos Position of item to be removed.
Returns:
Pointer to the object stored in the node
POS should be a valid node index from 0 to count-1, or the value -1 which causes the node at the current position to be removed (this allows a node to be removed without having to know its absolute position in the list). A pointer to the object referenced by the deleted node is returned upon successful completion, otherwise NULL is returned. POS is left pointing to the element preceding the deleted element.
References vll_rebuild_index(), and vll_seek().
obj vll_seek (vocList_t * list, long offset, int whence)
Seek to the indicated position in the list.
vll_seek -- Seek to the indicated position in the list.
Parameters:
list Linked list to be accessed
offset Offset from the given position
whence Reference position for seek
Returns:
Pointer to the object stored at that node
The current position in the list is set to the node OFFSET positions from the reference point indicated by WHENCE: SEEK_SET (beginning of list), SEEK_CUR (current position), SEEK_END (end of list). The values of WHENCE are as defined in <stdio.h>. A seek to (0,SEEK_SET) positions to the beginning of the list, whereas (0,SEEK_END) positions ot the end of the list.
If the seek position is valid a pointer to the object at that location is returned, otherwise NULL. A seek on an empty list always returns NULL since there is no object pointer to return. The current list position is unaffected if NULL is returned.
Referenced by vll_next(), vll_prev(), and vll_remove().