#!/bin/csh -f

#set top = `(chdir .. ; pwd)`
set top = `pwd`

setenv CC 	"gcc"
setenv CXX 	"g++"


if ($?PLMACH) then
  if ($PLMACH == "macosx") then
    setenv CFLAGS "-arch i386 -arch ppc -m32 -mmacosx-version-min=10.4 -DDarwin"
  endif
endif


echo "Building CFITSIO libraries ...."
echo "  (Using toplevel directory '"$top"' ....)"

# Global options.
set	gopts = "--prefix=$top --exec-prefix=$top --disable-shared"

./configure $gopts  				 >& _spool
make clean 					>>& _spool
make 						>>& _spool

ar   rv ../libsamp.a *.o			>>& _spool2
cp   fitsio*.h longnam.h ../../include

make clean
echo "done"

