.\" @(#)vospectrum.1 1.0 July-2012 MJF
.TH VOSPECTRUM 1 "July 2012" "VOClient Package"
.SH NAME
vospectrum \- short description
.SH SYNOPSIS
\fBvospectrum\fP [\-\fopts\fP] file

.SH OPTIONS
The \fIvospectrum\fP application accepts the following options:
.TP 8
.B \-h, --help
Print a help summary to the terminal and exit.  No processing is done 
following this flag.

.SH DESCRIPTION
The \fIvospectrum\fP application ......
.PP
More descriptions .....

.SH SUB-DESCRIPTION
More useful stuff .......


.SH RETURN STATUS
On exit the vospectrum will return the following status codes:
.nf
     0 Success
     1 Error code
.fi


.SH EXAMPLES
.TP 4
1) Queue a file for transport:
.nf
	% vospectrum .....
.fi


.SH BUGS
The VOSPECTRUM .....


.SH Revision History
July 2012 - First public release
.SH Author
Michael Fitzpatrick (fitz@noao.edu), July 2012
.SH "SEE ALSO"

